const {test}=require('node:test'),assert=require('node:assert/strict'),P=require('../public/research-r199-portfolio.js'),fs=require('node:fs'),vm=require('node:vm');
const p={initial:1000,roi:10,maxDrawdown:5,curve:[{date:'2024-01-02'},{date:'2024-01-03'},{date:'2024-01-04'}]};const rows=[{date:'2024-01-01',close:100},{date:'2024-01-02',close:110},{date:'2024-01-03',close:90},{date:'2024-01-04',close:120}];
test('benchmark uses previous close and exact portfolio dates, same capital, drawdown and arithmetic excess',()=>{const b=P.benchmark(p,rows,'2024-01-01');assert.equal(b.ok,true);assert.ok(Math.abs(b.roi-20)<1e-9);assert.ok(Math.abs(b.excessReturn+10)<1e-9);assert.ok(Math.abs(b.maxDrawdown-200/1100*100)<1e-9);assert.equal(b.netProfit,200);assert.equal(b.curve[0].equity,1100);assert.ok(Math.abs(b.monthly[0].returnPct-20)<1e-9);});
test('missing base, intermediate date or duplicates refuse comparison without shortening period',()=>{assert.equal(P.benchmark(p,rows.slice(1),'2024-01-01').ok,false);assert.equal(P.benchmark(p,rows.filter(x=>x.date!=='2024-01-03'),'2024-01-01').ok,false);assert.equal(P.benchmark(p,[...rows,rows[0]],'2024-01-01').ok,false);});
test('benchmark route reads cache without network and downloads exact unrounded index with no FinMind',async()=>{
 const store=new Map(),calls=[],src=fs.readFileSync('src/index.js','utf8').replace('export default {','globalThis.worker = {');
 const ctx=vm.createContext({URL,URLSearchParams,Request,Response,Headers,AbortSignal,console,caches:{default:{async match(k){return store.get(k.url)?.clone()},async put(k,r){store.set(k.url,r.clone())}}},fetch:async u=>{calls.push(u);return new Response(JSON.stringify({chart:{result:[{meta:{symbol:'^TWII'},timestamp:[Date.parse('2024-01-02')/1000],indicators:{quote:[{close:[17532.123]}]}}]}}));}});vm.runInContext(src,ctx);
 async function req(method){const u=new URL('https://test/api/research/benchmark?start_date=2024-01-01&end_date=2024-01-04'),r=await ctx.worker.fetch(new Request(u,{method}),{});return {status:r.status,j:await r.json()};}
 assert.equal((await req('GET')).status,404);assert.equal(calls.length,0);const b=await req('POST');assert.equal(b.status,200);assert.equal(b.j.data[0].close,17532.123);assert.equal(b.j.returnType,'price');await req('POST');await req('GET');assert.equal(calls.length,1);assert.ok(!calls[0].includes('finmind'));
});
test('official fallback validates month and preserves TAIEX decimals',async()=>{
 const src=fs.readFileSync('src/index.js','utf8').replace('export default {','globalThis.worker = {'),calls=[];
 const ctx=vm.createContext({URL,URLSearchParams,Request,Response,Headers,AbortSignal,console,caches:{default:{async match(){},async put(){}}},fetch:async u=>{calls.push(u);if(u.includes('yahoo'))return new Response('{}',{status:429});return new Response(JSON.stringify({date:'20240101',fields:['日期','發行量加權股價指數'],data:[['113/01/02','17,532.53']]}));}});vm.runInContext(src,ctx);const u=new URL('https://test/api/research/benchmark?start_date=2024-01-01&end_date=2024-01-04'),r=await ctx.worker.fetch(new Request(u,{method:'POST'}),{}),j=await r.json();assert.equal(r.status,200);assert.equal(j.source,'TWSE FMTQIK');assert.equal(j.data[0].close,17532.53);assert.equal(calls.length,3);
});
