// Generated by scripts/build-scan-runtime.cjs. Do not edit by hand.
const TWAction=(()=>{const root={};
  'use strict';
  const key='twq_action_weights_v1160r2';
  const keys=['entry','setup','opportunity','hold'];
  const defaults={entry:40,setup:30,opportunity:30,hold:0};
  function valid(w){return !!w&&keys.every(k=>Number.isFinite(w[k])&&w[k]>=0&&w[k]<=100)&&Math.abs(keys.reduce((s,k)=>s+w[k],0)-100)<1e-9}
  function read(){
    try{const x=JSON.parse(root.localStorage.getItem(key)||'null');if(!x)return {...defaults};
      const w=Object.fromEntries(keys.map(k=>[k,Number(x[k]??(k==='hold'?0:NaN))]));
      return valid(w)?w:{...defaults};
    }catch(e){return {...defaults}}
  }
  function score(s,w=read()){
    if(!valid(w)||!s)return null;
    if(!keys.every(k=>w[k]===0||(s[k]!=null&&Number.isFinite(Number(s[k])))))return null;
    return Math.round(keys.reduce((sum,k)=>sum+(w[k]===0?0:Number(s[k])*w[k]/100),0));
  }
  function delta(s,p,w=read()){const a=score(s,w),b=score(p,w);return a==null||b==null?null:a-b}
  function save(w){if(!valid(w))return false;try{const raw=JSON.stringify(w);if(root.localStorage.getItem(key)!==raw)root.localStorage.setItem(key,raw)}catch(e){}return true}
  root.TWAction={key,keys,defaults,valid,read,score,delta,save};

return root.TWAction;})();
const TWHoldChange=(()=>{const root={};
  'use strict';
  const schema='hold-change-r21';
  const valid=Number.isFinite;
  function calculate(current,previous,currentVolume,previousVolume){
    const holdDelta=valid(current?.hold)&&valid(previous?.hold)?current.hold-previous.hold:null;
    const holdVolumeRatio=valid(currentVolume)&&currentVolume>=0&&valid(previousVolume)&&previousVolume>0
      ?currentVolume/previousVolume:null;
    const holdVolumeBonus=holdVolumeRatio===null?null:
      holdVolumeRatio>=2?10:holdVolumeRatio>=1.5?7:holdVolumeRatio>=1.2?4:holdVolumeRatio<0.6?-4:0;
    return {
      holdDelta,holdVolumeRatio,holdVolumeBonus,
      holdVolumeChangePct:holdVolumeRatio===null?null:(holdVolumeRatio-1)*100,
      holdVolumeDelta:holdDelta===null||holdVolumeBonus===null?null:holdDelta+holdVolumeBonus
    };
  }
  function signed(value,digits=0){
    if(!valid(value))return '—';
    const rounded=Number(value.toFixed(digits));
    return (rounded>0?'+':'')+rounded.toFixed(digits);
  }
  function volumeText(change,projected=false){
    if(!valid(change?.holdVolumeRatio))return '前一交易日成交量不足，暫無法比較';
    return `${projected?'預估量':'成交量'}較前交易日 ${signed(change.holdVolumeChangePct,1)}%（${change.holdVolumeRatio.toFixed(2)}×）｜量能 ${signed(change.holdVolumeBonus)} 分`;
  }
  root.TWHoldChange={schema,calculate,signed,volumeText};

return root.TWHoldChange;})();
const TWDualAction=(()=>{const root={};
  'use strict';
  const key='twq_dual_action_r24',schema='dual-action-r26';
  const keys=['setup','opportunity','entry','hold'];
  const defaults={buy:{setup:0,opportunity:20,entry:25,hold:55},stay:{setup:20,opportunity:0,entry:0,hold:80}};
  const copy=x=>JSON.parse(JSON.stringify(x));
  const validWeight=w=>!!w&&keys.every(k=>Number.isFinite(w[k])&&w[k]>=0&&w[k]<=100)&&Math.abs(keys.reduce((n,k)=>n+w[k],0)-100)<1e-9;
  const valid=w=>!!w&&validWeight(w.buy)&&validWeight(w.stay);
  function read(){try{const w=JSON.parse(root.localStorage.getItem(key));return valid(w)?w:copy(defaults)}catch{return copy(defaults)}}
  function save(w){if(!valid(w))return false;try{root.localStorage.setItem(key,JSON.stringify(w));return true}catch{return false}}
  function score(s,w){if(!s||!validWeight(w)||!keys.every(k=>w[k]===0||Number.isFinite(s[k])))return null;return Math.round(keys.reduce((a,k)=>a+(w[k]?s[k]*w[k]/100:0),0))}
  // Use the same volume confirmation bands as Hold + volume. Never invent a
  // zero bonus when the previous completed session's volume is unavailable.
  function volumeBonus(r){
    const ratio=Number.isFinite(r?.holdVolumeRatio)?r.holdVolumeRatio:
      Number.isFinite(r?.volume)&&r.volume>=0&&Number.isFinite(r?.previousVolume)&&r.previousVolume>0?r.volume/r.previousVolume:null;
    return ratio===null?null:ratio>=2?10:ratio>=1.5?7:ratio>=1.2?4:ratio<0.6?-4:0;
  }
  function metrics(r,w=read()){
    const empty={buy:null,buyDelta:null,stay:null,stayDelta:null,stayDrop:null,buyScoreDelta:null,stayScoreDelta:null,volumeBonus:null};
    if(!valid(w)||r?.holdNeedsRefresh)return empty;
    const buy=score(r,w.buy),stay=score(r,w.stay),pb=score(r?.previousScores,w.buy),ps=score(r?.previousScores,w.stay);
    const trail=r?.actionTrail||[],values=trail.map(x=>score(Object.fromEntries(keys.map((k,i)=>[k,x[i]])),w.stay));
    const stayDrop=stay!==null&&values.length===5&&values.every(Number.isFinite)?Math.max(0,Math.max(...values)-stay):null;
    const bonus=volumeBonus(r),buyScoreDelta=buy!==null&&pb!==null?buy-pb:null,stayScoreDelta=stay!==null&&ps!==null?stay-ps:null;
    return {buy,stay,buyScoreDelta,stayScoreDelta,volumeBonus:bonus,
      buyDelta:buyScoreDelta!==null&&bonus!==null?buyScoreDelta+bonus:null,
      stayDelta:stayScoreDelta!==null&&bonus!==null?stayScoreDelta+bonus:null,stayDrop};
  }
  const selections={buyAction:'buy',buyActionDelta:'buyDelta',stayAction:'stay',stayActionDelta:'stayDelta',stayDrawdown:'stayDrop'};
  function rank(r,k,w){const v=metrics(r,w)[selections[k]];return k==='stayActionDelta'&&v!==null?-v:v}
  function history(rows,scoreAt){return rows.length>=70?Array.from({length:5},(_,i)=>{const a=rows.slice(0,rows.length-5+i),s=scoreAt(a);return keys.map(k=>s[k])}):[]}
  const number=v=>v===null||v===undefined||v===''?NaN:Number(String(v).replace(/,/g,''));
  function net(r,p){const b=number(r?.[p+'_buy']),s=number(r?.[p+'_sell']);return Number.isFinite(b)&&Number.isFinite(s)?b-s:null}
  function absorption(rows,inst=[]){
    const priceDate=rows.at(-1)?.date||null,projected=!!rows.at(-1)?.intradayProjected;
    const empty={state:'資料不足',detail:'需要連續5個交易日外資與投信買賣超及對應成交量',priceDate,chipDate:null,lag:null,projected,scored:false};
    if(rows.length<25)return empty;
    // Match actual trading dates; never count an absent observation as zero.
    const map=new Map();for(const r of inst){if(r.date<=priceDate&&(!projected||r.date<priceDate))map.set(r.date,r)}
    const index=rows.findLastIndex(r=>map.has(r.date));
    if(index<0)return empty;
    const chipDate=rows[index].date,lag=rows.length-1-index;
    const a=rows.slice(index-4,index+1),matched=a.map(r=>map.get(r.date));
    const out={...empty,chipDate,lag};
    if(index<24||a.length!==5||matched.some(r=>!r))return out;
    const foreign=matched.map(r=>net(r,'Foreign_Investor')),trust=matched.map(r=>net(r,'Investment_Trust'));
    if([...foreign,...trust].some(x=>x===null)||a.some(r=>!(number(r.volume)>0)))return out;
    const total=foreign.map((f,i)=>f+trust[i]),volume=a.reduce((s,r)=>s+number(r.volume),0),net5=total.reduce((a,b)=>a+b,0);
    const base=rows[index-5],before=rows.slice(index-24,index-4),support=Math.min(...before.map(r=>number(r.low))),ceiling=Math.max(...before.map(r=>number(r.high)));
    const endpoint=a.at(-1),ret=(endpoint.close/base.close-1)*100,ratio=net5/volume*100;
    let sellStreak=0;for(let i=4;i>=0&&total[i]<0;i--)sellStreak++;
    const meaningful=ratio<=-3&&sellStreak>=3;
    const lowerFailed=a.some(r=>r.low<support*.995),held=!lowerFailed&&Math.min(...a.map(r=>r.close))>=base.close*.985;
    const wickWarnings=a.filter((r,i)=>{const earlier=rows.slice(index-4+i-5,index-4+i),avg=earlier.reduce((s,x)=>s+x.volume,0)/earlier.length;return r.volume>=avg*1.5&&(r.high-Math.max(r.open,r.close))/Math.max(r.high-r.low,.01)>.45}).length;
    const declining=a.slice(1).every((r,i)=>r.low<a[i].low);
    let state='中性',detail='未形成連續實質賣壓；不推定承接';
    if(meaningful){
      if(lowerFailed){state='承接失敗';detail='連續賣超且跌破觀察前20日低點';}
      else if(wickWarnings>=2||declining||ret< -1.5){state='賣壓警戒';detail='連續賣超，伴隨反覆放量上影或價格走弱';}
      else if(held&&ret>=-1&&endpoint.close>ceiling){state='承接確認';detail='賣壓下守穩，且突破觀察前20日高點；仍不是未來上漲保證';}
      else if(held&&ret>=-1){state='承接觀察';detail='連續賣超但價格守穩；尚未確認突破';}
      else {state='賣壓警戒';detail='連續賣超，承接條件未完整';}
    }
    const latest=rows.at(-1),currentBroken=lag>0&&latest.low<support*.995;
    if(lag>0&&meaningful&&!currentBroken&&latest.close<endpoint.close*.985){state='賣壓警戒';detail='法人資料日曾守穩，但最新價格已轉弱';}
    if(currentBroken&&meaningful){state='承接失敗';detail='先前連續賣超後，最新價格已跌破觀察支撐';}
    if(lag>1){state='資料落後';detail='法人資料落後超過1個交易日，不判定目前承接狀態';}
    return {...out,state,detail,net5,ratio,return5:ret,sellStreak,support,foreign5:foreign.reduce((a,b)=>a+b,0),trust5:trust.reduce((a,b)=>a+b,0)};
  }
  // R31: compare the average flow level at all price-matched historical closes.
  // Taking differences eliminates the arbitrary origin of a cumulative series.
  const samePriceDefaults={lookback:60,tolerance:5,minGap:5};
  function samePriceOptions(raw={}){
    const pick=(key,min,max)=>Number.isFinite(Number(raw[key]))&&Number(raw[key])>=min&&Number(raw[key])<=max?Number(raw[key]):samePriceDefaults[key];
    return {lookback:Math.floor(pick('lookback',5,120)),tolerance:pick('tolerance',1,10),minGap:Math.floor(pick('minGap',1,20))};
  }
  function readSamePrice(){try{return samePriceOptions(JSON.parse(root.localStorage.getItem('twq_same_price_r31'))||{})}catch{return {...samePriceDefaults}}}
  function samePrice(rows,inst=[],options={}){
    const settings=samePriceOptions(options),current=rows.at(-1),priceDate=current?.date||null,projected=!!current?.intradayProjected;
    const empty={schema:'same-price-r31',settings,score:null,state:'資料不足',detail:'需要完整區間外資＋投信買賣超與20日成交量；缺值不補0',priceDate,projected,chipDate:null,lag:null,proxy:true};
    const price=number(current?.close),last=rows.length-1;
    if(last<20||!(price>0))return empty;
    if(rows.some((r,i)=>!r.date||(i>0&&r.date<=rows[i-1].date)))return {...empty,detail:'日K日期重複或未依日期遞增'};
    const map=new Map();
    for(const r of inst){if(r.date<=priceDate&&(!projected||r.date<priceDate)){
      if(map.has(r.date))return {...empty,detail:'法人日期重複，請更新資料'};
      map.set(r.date,r);
    }}
    const end=rows.findLastIndex(r=>map.has(r.date));
    if(end<0)return empty;
    const out={...empty,chipDate:rows[end].date,lag:last-end};
    // After close, yesterday's observation must never count as today's final score.
    if(end!==(projected?last-1:last))return {...out,state:'資料落後',detail:projected?'盤中需前一交易日完整法人資料':'尚未取得所選交易日盤後法人資料，請更新籌碼'};
    if(last<settings.lookback)return {...out,detail:`日K不足${settings.lookback}個回看交易日，請載入更多歷史`};
    const bases=[];
    for(let j=Math.max(0,last-settings.lookback);j<=last-settings.minGap;j++){
      const p=number(rows[j].close);
      if(j<end&&p>0&&Math.abs(price/p-1)<=settings.tolerance/100+1e-10)bases.push(j);
    }
    if(!bases.length)return {...out,state:'無同價位基準',sampleCount:0,detail:`前${settings.minGap}～${settings.lookback}個交易日內沒有價差±${settings.tolerance}%的收盤價`};
    const first=bases[0],suffix=new Map();let fsum=0,tsum=0,vsum=0,missing=0,recent5=0;
    for(let j=end;j>first;j--){
      const p=rows[j],r=map.get(p.date),f=net(r,'Foreign_Investor'),t=net(r,'Investment_Trust'),v=number(p.volume);
      if(!(number(p.close)>0)||Math.abs(number(p.close)/number(rows[j-1].close)-1)>.20)return {...out,state:'價格不可比',detail:'區間出現超過20%跳價，請先確認除權息／增減資與價格口徑'};
      if(f===null||t===null||!(v>0)||(r?._reportedGroups&&(!r._reportedGroups.includes('foreign')||!r._reportedGroups.includes('trust')))){missing++;continue;}
      fsum+=f;tsum+=t;vsum+=v;suffix.set(j-1,{f:fsum,t:tsum,v:vsum});
    }
    const meta={...out,sampleCount:bases.length,referenceDate:rows[bases.at(-1)].date,referenceStart:rows[first].date,referenceEnd:rows[bases.at(-1)].date,
      referencePrice:bases.reduce((s,j)=>s+number(rows[j].close),0)/bases.length,currentPrice:price};
    if(missing)return {...meta,missingDays:missing,detail:`比較區間缺少${missing}個交易日完整法人或成交量，請更新籌碼`};
    if(last>end&&Math.abs(price/number(rows[end].close)-1)>.20)return {...meta,state:'價格不可比',detail:'最新價格跳動超過20%，請確認價格口徑'};
    const avgRows=rows.slice(end-19,end+1);
    if(avgRows.length<20||avgRows.some(r=>!(number(r.volume)>0)))return {...meta,detail:'缺少完整20日實際成交量，無法標準化排序'};
    const averageVolume=avgRows.reduce((s,r)=>s+number(r.volume),0)/20;
    for(let j=end-4;j<=end;j++){
      const r=map.get(rows[j]?.date),f=net(r,'Foreign_Investor'),t=net(r,'Investment_Trust');
      if(f===null||t===null||(r?._reportedGroups&&(!r._reportedGroups.includes('foreign')||!r._reportedGroups.includes('trust')))){recent5=null;break;}
      recent5+=f+t;
    }
    const samples=bases.map(j=>{const x=suffix.get(j);return {date:rows[j].date,price:number(rows[j].close),days:end-j,netShares:x.f+x.t,foreignShares:x.f,trustShares:x.t,volume:x.v}});
    const mean=k=>samples.reduce((s,x)=>s+x[k],0)/samples.length;
    const netShares=mean('netShares'),foreignShares=mean('foreignShares'),trustShares=mean('trustShares'),volume=mean('volume'),strength=netShares/averageVolume;
    const score=Math.round(Math.max(0,Math.min(100,50+10*strength)));
    const support=Math.min(...rows.slice(-21,-1).map(r=>number(r.low))),broken=Number.isFinite(support)&&price<support;
    return {...meta,score,netShares,foreignShares,trustShares,volume,averageVolume,strength,samples,intervalDays:mean('days'),ratioPct:netShares/volume*100,
      priceChangePct:(price/meta.referencePrice-1)*100,recent5,support,broken,missingDays:0,
      state:netShares>0?'同價位增持':netShares<0?'同價位減持':'籌碼持平',
      detail:broken?'價格跌破前20日低點，需另外留意':recent5!==null&&recent5<0?'近5日轉為淨賣超':'比較相近價位平均籌碼水位；分數不是勝率'};
  }
  function samePriceNote(a){
    if(!a||a.schema!=='same-price-r31')return '待重新計算｜請更新籌碼或重新掃描';
    const head=`${a.state}｜${a.projected?'盤中參考・':'盤後・'}法人截至 ${a.chipDate||'—'}｜價格 ${a.priceDate||'—'}`;
    if(a.score===null)return head+'｜'+a.detail;
    const lots=v=>(v>0?'+':'')+(v/1000).toLocaleString('zh-TW',{maximumFractionDigits:1});
    return head+`｜較相近價位平均增減 ${lots(a.netShares)} 張（${a.strength.toFixed(2)}倍20日均量）｜${a.sampleCount}個比對日：${a.referenceStart}～${a.referenceEnd}，均價${a.referencePrice.toFixed(2)}元｜外資 ${lots(a.foreignShares)}、投信 ${lots(a.trustShares)} 張｜`+a.detail;
  }
  const signed=v=>Number.isFinite(v)?(v>0?'+':'')+v:'—';
  function note(a){if(!a)return '待更新｜重新掃描或更新盤中行情';return `${a.state}｜法人截至 ${a.chipDate||'—'}${a.lag?'（落後 '+a.lag+' 個交易日）':''}｜${a.detail}。外資＋投信，排除自營商；尚未計入加減分。`}
  root.TWDualAction={key,schema,keys,defaults,valid,validWeight,read,save,score,volumeBonus,metrics,selections,rank,history,absorption,samePriceDefaults,samePriceOptions,readSamePrice,samePrice,samePriceNote,signed,note};

return root.TWDualAction;})();
const num=x=>Number(String(x??0).replace(/,/g,''))||0;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const fmt=(x,d=1)=>Number.isFinite(x)?Number(x).toLocaleString('zh-TW',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const pct=(x,d=1)=>Number.isFinite(x)?`${x>=0?'+':''}${x.toFixed(d)}%`:'—';
const tick=p=>p<10?.01:p<50?.05:p<100?.1:p<500?.5:p<1000?1:5;
const roundTick=p=>{const t=tick(p);return Math.round(p/t)*t};
const dateISO=d=>d.toISOString().slice(0,10);
const today=()=>{const d=new Date();return dateISO(new Date(d.getFullYear(),d.getMonth(),d.getDate()))};
const daysAgo=n=>{const d=new Date();d.setDate(d.getDate()-n);return dateISO(d)};
const sum=a=>a.reduce((x,y)=>x+y,0);
const avg=a=>a.length?sum(a)/a.length:NaN;
const last=a=>a[a.length-1];
const uniq=a=>[...new Set(a)];
const signClass=x=>x>0?'green':x<0?'red':'yellow';

function scoreGrade(s){
  if(s>=90)return ['S','green']; if(s>=85)return ['A+','green']; if(s>=80)return ['A','green'];
  if(s>=70)return ['B','yellow']; if(s>=60)return ['C','yellow']; return ['D','red'];
}
function positionPct(s){
  if(s>=90)return '25–30%'; if(s>=80)return '15–20%'; if(s>=70)return '10%'; return '0%';
}
function normalizePrices(rows){
  return rows.map(r=>({date:r.date,open:num(r.open),high:num(r.max),low:num(r.min),close:num(r.close),volume:num(r.Trading_Volume),money:num(r.Trading_money)}))
    .filter(r=>r.close>0).sort((a,b)=>a.date.localeCompare(b.date));
}
function ma(rows,n,i=rows.length-1){
  if(i<n-1)return NaN;
  return avg(rows.slice(i-n+1,i+1).map(x=>x.close));
}
function smaSeries(rows,n){
  return rows.map((_,i)=>ma(rows,n,i));
}
function ema(values,n){
  const k=2/(n+1); let out=[],e=values[0];
  values.forEach((v,i)=>{e=i===0?v:v*k+e*(1-k);out.push(e)}); return out;
}
function calcRSI(rows,n=14){
  if(rows.length<n+1)return NaN; let g=0,l=0;
  for(let i=rows.length-n;i<rows.length;i++){let d=rows[i].close-rows[i-1].close;if(d>0)g+=d;else l-=d}
  if(l===0)return 100; const rs=(g/n)/(l/n); return 100-100/(1+rs);
}
function calcMACD(rows){
  if(rows.length<35)return {macd:NaN,signal:NaN,hist:NaN,prevHist:NaN};
  const c=rows.map(x=>x.close),e12=ema(c,12),e26=ema(c,26),m=c.map((_,i)=>e12[i]-e26[i]),sig=ema(m,9);
  return {macd:last(m),signal:last(sig),hist:last(m)-last(sig),prevHist:m[m.length-2]-sig[sig.length-2]};
}
function calcKD(rows,n=9){
  if(rows.length<n+2)return {k:NaN,d:NaN,pk:NaN,pd:NaN};
  let k=50,d=50,pk=50,pd=50;
  for(let i=n-1;i<rows.length;i++){
    pk=k;pd=d; const w=rows.slice(i-n+1,i+1),hh=Math.max(...w.map(x=>x.high)),ll=Math.min(...w.map(x=>x.low));
    const rsv=hh===ll?50:(rows[i].close-ll)/(hh-ll)*100; k=(2/3)*k+(1/3)*rsv; d=(2/3)*d+(1/3)*k;
  } return {k,d,pk,pd};
}
function calcBoll(rows,n=20){
  if(rows.length<n)return {mid:NaN,upper:NaN,lower:NaN};
  const a=rows.slice(-n).map(x=>x.close),m=avg(a),sd=Math.sqrt(avg(a.map(x=>(x-m)**2)));
  return {mid:m,upper:m+2*sd,lower:m-2*sd};
}
function atr(rows,n=14){
  if(rows.length<n+1)return NaN; let tr=[];
  for(let i=rows.length-n;i<rows.length;i++) tr.push(Math.max(rows[i].high-rows[i].low,Math.abs(rows[i].high-rows[i-1].close),Math.abs(rows[i].low-rows[i-1].close)));
  return avg(tr);
}
function percentile(arr,val){
  const a=arr.filter(Number.isFinite); if(a.length<2)return NaN;
  return a.filter(x=>x<=val).length/a.length*100;
}
function latestAtOrBefore(rows,date){const a=rows.filter(x=>x.date<=date);return a.length?last(a):null}
function cut(rows,date){return rows.filter(x=>x.date<=date)}
function instNetRow(r){
  const keys=['Foreign_Investor','Foreign_Dealer_Self','Investment_Trust','Dealer','Dealer_self','Dealer_Hedging'];
  return sum(keys.map(k=>num(r[k+'_buy'])-num(r[k+'_sell'])));
}
function instDetail(r){
  if(!r)return {foreign:NaN,trust:NaN,dealer:NaN,total:NaN};
  const foreign=num(r.Foreign_Investor_buy)-num(r.Foreign_Investor_sell)+num(r.Foreign_Dealer_Self_buy)-num(r.Foreign_Dealer_Self_sell);
  const trust=num(r.Investment_Trust_buy)-num(r.Investment_Trust_sell);
  const dealer=(num(r.Dealer_buy)-num(r.Dealer_sell))+(num(r.Dealer_self_buy)-num(r.Dealer_self_sell))+(num(r.Dealer_Hedging_buy)-num(r.Dealer_Hedging_sell));
  return {foreign,trust,dealer,total:foreign+trust+dealer};
}
function recentSwingLow(rows,look=35){
  const a=rows.slice(-look); let lows=[];
  for(let i=2;i<a.length-2;i++) if(a[i].low<=a[i-1].low&&a[i].low<=a[i-2].low&&a[i].low<=a[i+1].low&&a[i].low<=a[i+2].low) lows.push(a[i]);
  return lows.length?last(lows):a.reduce((m,x)=>x.low<m.low?x:m,a[0]);
}
function higherLow(rows){
  const a=rows.slice(-60),l=[];
  for(let i=2;i<a.length-2;i++)if(a[i].low<=a[i-1].low&&a[i].low<=a[i-2].low&&a[i].low<=a[i+1].low&&a[i].low<=a[i+2].low)l.push(a[i]);
  if(l.length<2)return {ok:false,a:null,b:null};
  const x=l[l.length-2],y=l[l.length-1];return {ok:y.low>x.low,a:x,b:y};
}
function recentGap(rows){
  const a=rows.slice(-25); let g=null;
  for(let i=1;i<a.length;i++)if(a[i].low>a[i-1].high)g={date:a[i].date,lower:a[i-1].high,upper:a[i].low};
  return g;
}
function supportBelow(price,cands){
  const x=cands.filter(v=>Number.isFinite(v)&&v>0&&v<price).sort((a,b)=>b-a);
  return x.length?x[0]:price*0.96;
}
function computeTargets(rows,entry){
  const prev=rows.slice(-90,-1),cur=last(rows),visibleHigh=prev.length?Math.max(...prev.map(x=>x.high)):cur.high;
  const box=rows.slice(-30),boxHigh=Math.max(...box.map(x=>x.high)),boxLow=Math.min(...box.map(x=>x.low)),range=Math.max(boxHigh-boxLow,atr(rows)*4||entry*.08);
  if(cur.close>=visibleHigh*0.995){
    return {t1:roundTick(entry+range*.618),t2:roundTick(entry+range*1.618),mode:'可視區間新高：箱體 0.618 / 1.618 延伸'};
  }
  let t1=visibleHigh>entry?visibleHigh:entry+range*.618;
  return {t1:roundTick(t1),t2:roundTick(Math.max(t1+range*.618,entry+range*1.2)),mode:'左側可視前高 + 延伸'};
}
function riskRR(entry,stop,t1,t2){
  const risk=(entry-stop)/entry*100,den=entry-stop;
  return {risk,rr1:den>0?(t1-entry)/den:NaN,rr2:den>0?(t2-entry)/den:NaN};
}

function recentEventKSupport(rows,lookback=8){
  const lb=Math.min(lookback,rows.length-1);
  for(let age=0;age<=lb;age++){
    const k=rows.length-1-age;
    if(k<1)break;
    const r=rows[k],p=rows[k-1];
    const dr=(r.close/p.close-1)*100;
    const base=rows.slice(Math.max(0,k-5),k);
    const av=avg(base.map(z=>z.volume))||r.volume||1;
    const rg=Math.max(r.high-r.low,tick(r.close));
    const loc=(r.close-r.low)/rg;
    const isEvent=r.close>=r.open && loc>=.62 &&
      ((dr>=5 && r.volume/av>=1.0) || (dr>=3.5 && r.volume/av>=1.35) || dr>=8.5);
    if(isEvent)return {age,date:r.date,low:r.low,high:r.high,close:r.close,volume:r.volume};
  }
  return null;
}

function evaluate(rows,margin,inst,daytrade,entryMode='market'){
  const cur=last(rows),close=cur.close,ma5=ma(rows,5),ma10=ma(rows,10),ma20=ma(rows,20),ma60=ma(rows,60);
  const hl=higherLow(rows),swing=recentSwingLow(rows),gap=recentGap(rows);
  const prevHigh=Math.max(...rows.slice(-61,-1).map(x=>x.high));
  const breakoutSupport=close>prevHigh ? prevHigh : NaN;
  let candidates=uniq([ma5,ma10,ma20,breakoutSupport,gap?.lower].filter(Number.isFinite).map(roundTick)).filter(x=>x<close*1.002&&x>close*.82);
  if(!candidates.length)candidates=[roundTick(ma10||close*.97)];

  // V1.12 Structural-Safe Optimal Entry
  const eventK=recentEventKSupport(rows,8);
  const platformVals=[breakoutSupport,gap?.lower].filter(Number.isFinite);
  const platformFloor=platformVals.length?Math.max(...platformVals):NaN;
  const structuralGuard={
    eventLow:eventK?.low ?? NaN,
    eventDate:eventK?.date ?? null,
    hlLow:hl.b?.low ?? NaN,
    swingLow:swing?.low ?? NaN,
    platformFloor,
    ma10,ma20
  };
  const structuralSafeFor=(e)=>{
    if(Number.isFinite(structuralGuard.eventLow) && e<=structuralGuard.eventLow*1.003)return false;
    if(Number.isFinite(structuralGuard.hlLow) && e<=structuralGuard.hlLow*1.003)return false;
    if(Number.isFinite(structuralGuard.swingLow) && e<=structuralGuard.swingLow*1.001)return false;
    if(Number.isFinite(structuralGuard.platformFloor) && e<structuralGuard.platformFloor*.997)return false;
    return true;
  };

  const safeFloors=[
    Number.isFinite(structuralGuard.eventLow)?structuralGuard.eventLow*1.003:NaN,
    Number.isFinite(structuralGuard.hlLow)?structuralGuard.hlLow*1.003:NaN,
    Number.isFinite(structuralGuard.swingLow)?structuralGuard.swingLow*1.001:NaN,
    Number.isFinite(structuralGuard.platformFloor)?structuralGuard.platformFloor*.997:NaN
  ].filter(Number.isFinite);
  const safeFloor=safeFloors.length?Math.max(...safeFloors):NaN;
  if(Number.isFinite(safeFloor)&&safeFloor<close){
    const lo=roundTick(safeFloor+tick(safeFloor)),span=Math.max(0,close-lo),grid=[];
    for(let k=0;k<=20;k++){const p=roundTick(lo+span*k/20);if(p>0&&p<=close*1.002)grid.push(p)}
    candidates=uniq([...candidates,...grid]);
    structuralGuard.safeFloor=lo;
  }else structuralGuard.safeFloor=NaN;

  const baseStopFor=(entry)=>roundTick(supportBelow(entry,[ma20,ma10,hl.b?.low,swing?.low,breakoutSupport]) - tick(entry));
  let bestAll=null,bestSafe=null;
  for(const e0 of candidates){
    const e=roundTick(e0),stop=baseStopFor(e),tg=computeTargets(rows,e),rr=riskRR(e,stop,tg.t1,tg.t2);
    let s=100-Math.max(0,rr.risk-4)*5 + Math.min(8,Math.max(-8,(rr.rr2-3)*4));
    if(rr.risk<=4)s+=5;if(rr.rr1>=1.5)s+=4;if(rr.rr2>=3)s+=6;
    const candidate={entry:e,stop,...tg,...rr,rank:s,structuralSafe:structuralSafeFor(e)};
    if(!bestAll||s>bestAll.rank)bestAll=candidate;
    if(candidate.structuralSafe&&(!bestSafe||s>bestSafe.rank))bestSafe=candidate;
  }
  const best=bestSafe||bestAll;
  structuralGuard.hasSafeCandidate=!!bestSafe;
  structuralGuard.selectedSafe=!!best?.structuralSafe;
  const marketEntry=close;
  const marketStop=baseStopFor(marketEntry),marketT=computeTargets(rows,marketEntry),marketRR=riskRR(marketEntry,marketStop,marketT.t1,marketT.t2);
  const entry=entryMode==='optimal'?best.entry:marketEntry;
  const stop=entryMode==='optimal'?best.stop:marketStop;
  const tg=entryMode==='optimal'?best:({...marketT,...marketRR});
  const bias=(entry-ma20)/ma20*100;
  const vol5=avg(rows.slice(-6,-1).map(x=>x.volume)),volRatio=vol5?cur.volume/vol5:NaN;
  const rsi=calcRSI(rows),macd=calcMACD(rows),kd=calcKD(rows),boll=calcBoll(rows);
  const day=latestAtOrBefore(daytrade,cur.date),dayRatio=day&&cur.volume?num(day.Volume)/cur.volume*100:NaN;
  const m=latestAtOrBefore(margin,cur.date);
  const mVals=margin.slice(-90).map(x=>num(x.MarginPurchaseTodayBalance)).filter(x=>x>0);
  const marginPct=m?percentile(mVals,num(m.MarginPurchaseTodayBalance)):NaN;
  const marginChg=m&&num(m.MarginPurchaseYesterdayBalance)?(num(m.MarginPurchaseTodayBalance)-num(m.MarginPurchaseYesterdayBalance))/num(m.MarginPurchaseYesterdayBalance)*100:NaN;
  const ir=latestAtOrBefore(inst,cur.date),id=instDetail(ir),instConc=cur.volume?id.total/cur.volume*100:NaN;
  let cum=0,incs=inst.slice(-90).map(x=>cum+=instNetRow(x)),instPct=incs.length?percentile(incs,last(incs)):NaN;
  const body=Math.abs(cur.close-cur.open),range=Math.max(cur.high-cur.low,tick(cur.close)),upper=cur.high-Math.max(cur.open,cur.close),longUpper=upper/range>.45;
  const black=cur.close<cur.open,swallow=rows.length>1&&black&&cur.open>rows[rows.length-2].close&&cur.close<rows[rows.length-2].open;
  const hardBroken=cur.close<Math.min(ma10,ma20) || (hl.b&&cur.close<hl.b.low*.995);
  const prior5=rows.slice(-6,-1),priorVol=avg(prior5.map(x=>x.volume));
  const dry=volRatio<.65,attack=volRatio>=1.5&&cur.close>cur.open;
  const scoreItems=[];
  const add=(name,max,score,text,state='ok',available=true)=>scoreItems.push({name,max,score:available?clamp(score,0,max):null,text,state,available});

  let f1=0;if(close>ma20)f1+=3;if(ma5>ma10&&ma10>ma20)f1+=3;if(ma20>ma60)f1+=2;
  const ded20=rows.length>20?rows[rows.length-20].close:NaN;if(close>ded20)f1+=2;if(ma20>ma(rows.slice(0,-1),20))f1+=2;
  add('1. 均線幾何 / 扣抵',12,f1,`MA5 ${fmt(ma5)} / MA10 ${fmt(ma10)} / MA20 ${fmt(ma20)}；20MA 扣抵 ${fmt(ded20)}，${close>ded20?'扣低翻揚有利':'扣高壓力偏大'}`,f1>=8?'ok':f1>=5?'warn':'bad');

  let f2=2;if(hl.ok)f2+=3;if(close>prevHigh)f2+=2;if(cur.close>cur.open)f2+=1;if(longUpper||swallow)f2-=4;
  add('2. K線 / HL / 真偽突破',9,f2,`${hl.ok?'形成 Higher Low':'HL 尚未明確'}；${close>prevHigh?'突破可視前高':'未突破 60T 前高'}${longUpper?'；長上影風險':''}${swallow?'；黑K吞噬':''}`,f2>=6?'ok':f2>=3?'warn':'bad');

  let f3=3;if(attack)f3+=4;if(dry&&close>=ma10*.98)f3+=3;if(cur.volume<300000)f3-=5;
  add('3. 成交量 / 量價',9,f3,`今日量 ${(cur.volume/1000).toFixed(0)} 張；對 5T 均量 ${volRatio.toFixed(2)}x；${attack?'攻擊放量':dry?'量縮沉澱':'量能一般'}`,f3>=6?'ok':f3>=3?'warn':'bad');

  let f4=2;if(gap&&close>gap.lower)f4+=3;if(gap&&close<gap.lower)f4=0;if(close>ma5)f4+=1;
  add('4. 跳空缺口 / 貼身防守',6,f4,gap?`最近多方缺口 ${gap.date}，下緣 ${fmt(gap.lower)}；${close>gap.lower?'尚守住':'已跌破'}`:`近 25T 未偵測到明顯多方缺口；以 MA5/平台防守`,f4>=4?'ok':f4>=2?'warn':'bad');

  const f5Avail=!!ir;let f5=0;if(f5Avail){if(instConc>15)f5=8;else if(instConc>5)f5=6;else if(instConc>0)f5=4;else if(instConc<-10&&black)f5=0;else f5=2}
  add('5. 主力集中度代理',8,f5,f5Avail?`三大法人淨買賣 / 成交量 = ${pct(instConc)}。注意：這是法人集中代理，不是券商分點主力集中度。`:'法人資料未取得',f5>=5?'ok':f5>=3?'warn':'bad',f5Avail);

  const f6Avail=Number.isFinite(dayRatio);let f6=f6Avail?(dayRatio>50?1:dayRatio>35?3:5):0;
  add('6. 當沖率',5,f6,f6Avail?`當沖成交量占總量約 ${fmt(dayRatio,1)}%；${dayRatio>50?'籌碼穩定性偏低':'未觸發 >50% 警戒'}`:'當沖資料尚未更新/未提供',f6>=4?'ok':f6>=2?'warn':'bad',f6Avail);

  const f7Avail=!!m&&!!ir;let f7=0;if(f7Avail){f7+=(marginPct<30?5:marginPct<60?3:1);f7+=(instPct>70?5:instPct>40?3:1)}
  add('7. 融資 / 法人黃線百分位',10,f7,f7Avail?`融資餘額 ${num(m.MarginPurchaseTodayBalance).toLocaleString()} 張，90T 百分位 ${fmt(marginPct,0)}%；法人累積淨額 90T 百分位 ${fmt(instPct,0)}%`:'融資或法人序列不足',f7>=7?'ok':f7>=4?'warn':'bad',f7Avail);

  const f8Avail=!!ir;let f8=0;if(f8Avail){if(id.foreign>0)f8+=3;if(id.trust>0)f8+=3;if(id.dealer>0)f8+=2}
  add('8. 三大法人分類動向',8,f8,f8Avail?`外資 ${fmt(id.foreign/1000,0)} 張｜投信 ${fmt(id.trust/1000,0)} 張｜自營商 ${fmt(id.dealer/1000,0)} 張`:'法人資料未取得',f8>=5?'ok':f8>=3?'warn':'bad',f8Avail);

  add('9. 大戶持股 vs 散戶持股',5,0,'免費資料未取得「千張大戶持股比例 / 散戶股東人數」；本維度保留但不計分，不用法人/融資冒充真實股權分散。','warn',false);

  let f10=0;if(rsi>45&&rsi<72)f10+=2;if(macd.hist>0)f10+=2;if(macd.hist>macd.prevHist)f10+=1;if(kd.k>kd.d&&kd.k<85)f10+=1;if(close<boll.upper*1.01)f10+=1;
  add('10. KD / MACD / RSI / 布林',7,f10,`RSI14 ${fmt(rsi,1)}｜MACD Hist ${fmt(macd.hist,2)}｜KD ${fmt(kd.k,0)}/${fmt(kd.d,0)}｜布林上軌 ${fmt(boll.upper)}`,f10>=5?'ok':f10>=3?'warn':'bad');

  const risk=tg.risk;let f11=risk<=4?8:risk<=7?5:1;
  add('11. 防守深度 Risk%',8,f11,`進場 ${fmt(entry)} → 結構停損 ${fmt(stop)}，Risk ${fmt(risk,2)}%`,f11>=7?'ok':f11>=4?'warn':'bad');

  let f12=0;if(tg.rr1>=1.5)f12+=3;if(tg.rr2>=3)f12+=5;
  add('12. Target 1 / 2 與 R:R',8,f12,`T1 ${fmt(tg.t1)} = ${fmt(tg.rr1,2)}R｜T2 ${fmt(tg.t2)} = ${fmt(tg.rr2,2)}R；${tg.mode}`,f12>=6?'ok':f12>=3?'warn':'bad');

  let f13=5;if(hardBroken)f13=0;
  add('13. 防禦出場 / SOP',5,f13,hardBroken?'價格已摜破關鍵結構，買訊作廢。':`第一道以 MA5/缺口/突破平台減碼；第二道 ${fmt(stop)} 硬停損；隔日低開摜破前低或 MA5 作廢`,hardBroken?'bad':'ok');

  const availableMax=sum(scoreItems.filter(x=>x.available).map(x=>x.max));
  const got=sum(scoreItems.filter(x=>x.available).map(x=>x.score));
  let raw=availableMax?got/availableMax*100:0;
  if(bias>25)raw=Math.min(raw,58); else if(bias>15)raw=Math.min(raw,69);
  if(longUpper&&volRatio>1.5)raw=Math.min(raw,45);
  if(hardBroken)raw=0;
  const confidence=availableMax;
  return {
    score:Math.round(raw),items:scoreItems,availableMax,confidence,ma5,ma10,ma20,ma60,bias,volRatio,rsi,macd,kd,boll,hl,gap,
    entry,stop,t1:tg.t1,t2:tg.t2,risk:tg.risk,rr1:tg.rr1,rr2:tg.rr2,best,marketRR,marginPct,marginChg,instPct,instConc,id,dayRatio,
    hardBroken,longUpper,attack,dry,breakoutSupport,swing,prevHigh,structuralGuard
  };
}

function localLows(rows,look=80){
  const a=rows.slice(-look),out=[];
  for(let i=2;i<a.length-2;i++){
    if(a[i].low<=a[i-1].low&&a[i].low<=a[i-2].low&&a[i].low<=a[i+1].low&&a[i].low<=a[i+2].low){
      out.push({idx:rows.length-a.length+i,row:a[i]});
    }
  }
  return out;
}
function rsiAt(rows,idx,n=14){
  if(idx<n)return NaN;
  return calcRSI(rows.slice(0,idx+1),n);
}
function macdAt(rows,idx){
  if(idx<35)return {hist:NaN};
  return calcMACD(rows.slice(0,idx+1));
}
function bottomReversalEngine(rows,margin,inst,daytrade){
  const cur=last(rows), close=cur.close;
  const ma5v=ma(rows,5),ma10v=ma(rows,10),ma20v=ma(rows,20),ma60v=ma(rows,60);
  const rsi=calcRSI(rows),kd=calcKD(rows),macd=calcMACD(rows),boll=calcBoll(rows);
  const vol5=avg(rows.slice(-6,-1).map(x=>x.volume)),volRatio=vol5?cur.volume/vol5:NaN;
  const lows=localLows(rows,90),L2=lows.length?last(lows):null,L1=lows.length>1?lows[lows.length-2]:null;
  const low20=Math.min(...rows.slice(-20).map(x=>x.low)),low60=Math.min(...rows.slice(-60).map(x=>x.low));
  const high60=Math.max(...rows.slice(-60).map(x=>x.high));
  const drawdown=(close-high60)/high60*100;
  const bias20=(close-ma20v)/ma20v*100;
  const nearLow=(close-low60)/low60*100;
  const prev=rows[rows.length-2];
  const lowerWick=Math.min(cur.open,cur.close)-cur.low,range=Math.max(cur.high-cur.low,tick(close));
  const longLower=lowerWick/range>=0.35;
  const bullish=cur.close>cur.open;
  const reclaim5=cur.close>ma5v && prev.close<=ma(rows,5,rows.length-2);
  const reclaim10=cur.close>ma10v && prev.close<=ma(rows,10,rows.length-2);
  const panicVol=cur.volume>vol5*1.8 && cur.close>cur.low+(range*.55);
  const attack=volRatio>=1.35&&bullish;
  const dry=volRatio<=.70;
  const kdCross=kd.k>kd.d&&kd.pk<=kd.pd;
  const macdImprove=macd.hist>macd.prevHist;
  const rsiRecover=rsi>=30&&rsi<=58;

  // Price/momentum bullish divergence: second price low <= first, while RSI/MACD improves.
  let divergence=false,divText='未形成可確認底背離';
  if(L1&&L2&&L2.idx>L1.idx+3){
    const r1=rsiAt(rows,L1.idx),r2=rsiAt(rows,L2.idx);
    const h1=macdAt(rows,L1.idx).hist,h2=macdAt(rows,L2.idx).hist;
    const priceLower=L2.row.low<=L1.row.low*1.015;
    divergence=priceLower && ((Number.isFinite(r1)&&Number.isFinite(r2)&&r2>r1+2) || (Number.isFinite(h1)&&Number.isFinite(h2)&&h2>h1));
    divText=`低點 ${fmt(L1.row.low)} → ${fmt(L2.row.low)}；RSI ${fmt(r1,1)} → ${fmt(r2,1)}${divergence?'，出現動能底背離':'，背離不足'}`;
  }

  // Margin cleansing: compare latest to ~20 observations ago.
  const mm=margin.filter(x=>x.date<=cur.date),mNow=mm.length?num(last(mm).MarginPurchaseTodayBalance):NaN;
  const mOld=mm.length>15?num(mm[Math.max(0,mm.length-20)].MarginPurchaseTodayBalance):NaN;
  const mClean=Number.isFinite(mNow)&&Number.isFinite(mOld)&&mOld>0?(mNow-mOld)/mOld*100:NaN;
  const ii=inst.filter(x=>x.date<=cur.date),inst5=sum(ii.slice(-5).map(instNetRow)),instPrev5=sum(ii.slice(-10,-5).map(instNetRow));
  const instTurning=ii.length>=5 && (inst5>0 || inst5>instPrev5);

  // 6 independent factor groups = 100 points.
  let over=0;
  if(drawdown<=-15)over+=7; else if(drawdown<=-8)over+=4;
  if(bias20<=-10)over+=5; else if(bias20<=-5)over+=3;
  if(rsi<35)over+=5; else if(rsi<42)over+=3;
  if(close<=boll.lower*1.03)over+=3;
  over=clamp(over,0,20);

  let stopStruct=0;
  if(nearLow<=8)stopStruct+=4;
  if(longLower)stopStruct+=4;
  if(L1&&L2&&L2.row.low>=L1.row.low*.985)stopStruct+=6;
  if(reclaim5)stopStruct+=3;
  if(reclaim10)stopStruct+=3;
  stopStruct=clamp(stopStruct,0,20);

  let volume=0;
  if(panicVol)volume+=7;
  if(dry&&close>=low20*1.02)volume+=5;
  if(attack)volume+=8;
  else if(volRatio>=1.05&&bullish)volume+=4;
  volume=clamp(volume,0,20);

  let momentum=0;
  if(kdCross)momentum+=4;
  if(rsiRecover)momentum+=3;
  if(macdImprove)momentum+=3;
  if(divergence)momentum+=5;
  momentum=clamp(momentum,0,15);

  let chip=0,chipAvail=0;
  if(Number.isFinite(mClean)){chipAvail+=8;if(mClean<=-10)chip+=8;else if(mClean<=-4)chip+=5;else if(mClean<2)chip+=3}
  if(ii.length>=5){chipAvail+=7;if(instTurning)chip+=7;else if(inst5>instPrev5)chip+=4}
  // Missing chip data is neutral via normalization within this factor, capped at 15.
  chip = chipAvail ? chip/chipAvail*15 : 7.5;

  // Bottom stop: most recent structural low, with one tick buffer.
  const structLow=L2?.row.low || low20;
  const stop=roundTick(structLow-tick(structLow));
  const risk=(close-stop)/close*100;
  const resistance=Math.max(ma20v,ma60v,Math.max(...rows.slice(-30,-1).map(x=>x.high)));
  const reward=Math.max(0,resistance-close);
  const rr=(close-stop)>0?reward/(close-stop):0;
  let riskPts=0;
  if(risk>0&&risk<=4)riskPts+=5;else if(risk<=6.5)riskPts+=3;
  if(rr>=3)riskPts+=5;else if(rr>=1.8)riskPts+=3;else if(rr>=1.2)riskPts+=1;
  riskPts=clamp(riskPts,0,10);

  const factors=[
    ['超跌程度',over,20,`60T 高點回撤 ${pct(drawdown)}｜20MA Bias ${pct(bias20)}｜RSI ${fmt(rsi,1)}`],
    ['止跌結構',stopStruct,20,`${longLower?'長下影｜':''}${reclaim5?'站回MA5｜':''}${reclaim10?'站回MA10｜':''}${L1&&L2?`雙低 ${fmt(L1.row.low)} / ${fmt(L2.row.low)}`:'低點結構不足'}`],
    ['量價轉折',volume,20,`量比 ${fmt(volRatio,2)}x｜${panicVol?'恐慌換手':''}${dry?'量縮':''}${attack?'反攻放量':''}`],
    ['動能轉折',momentum,15,`KD ${fmt(kd.k,0)}/${fmt(kd.d,0)}｜MACD Hist ${fmt(macd.hist,2)}｜${divText}`],
    ['籌碼清洗',chip,15,`近20筆融資 ${Number.isFinite(mClean)?pct(mClean):'N/A'}｜近5日法人 ${fmt(inst5/1000,0)} 張`],
    ['底部風報比',riskPts,10,`前低停損 ${fmt(stop)}｜Risk ${fmt(risk,2)}%｜第一壓力 ${fmt(resistance)}｜R:R ${fmt(rr,2)}`]
  ];
  let score=Math.round(sum(factors.map(x=>x[1])));
  // Avoid calling a mature uptrend a "bottom" merely because momentum is strong.
  if(bias20>8 && nearLow>15) score=Math.min(score,64);
  // Falling knife veto: new 60d low + weak close + no divergence/reclaim.
  const fallingKnife=cur.low<=low60 && cur.close<cur.open && !divergence && !reclaim5;
  if(fallingKnife)score=Math.min(score,35);

  let stage='底部雷達',cls='yellow',position='0%';
  const rightFoot=L1&&L2&&L2.row.low>=L1.row.low*.985;
  const trigger=(reclaim10||attack) && (divergence||rightFoot||longLower);
  if(fallingKnife){stage='下跌刀口';cls='red';position='0%'}
  else if(score>=82 && trigger && risk<=6.5){stage='底部反轉買進';cls='green';position='15–20%'}
  else if(score>=70 && (rightFoot||divergence) && risk<=6.5){stage='底部試單';cls='green';position='5–10%'}
  else if(score>=58 && (longLower||reclaim5||macdImprove)){stage='止跌觀察';cls='yellow';position='0–5%'}
  else if(over>=10){stage='超跌雷達';cls='yellow';position='0%'}
  else {stage='非底部型態';cls='yellow';position='0%'}

  return {score,stage,cls,position,factors,stop,risk,rr,resistance,divergence,rightFoot,reclaim5,reclaim10,attack,fallingKnife,mClean,inst5,drawdown,bias20};
}


function ignitionEngine(rows,margin,inst){
  const cur=last(rows), prev=rows[rows.length-2], close=cur.close;
  const m5=ma(rows,5),m10=ma(rows,10),m20=ma(rows,20),m60=ma(rows,60);
  const pm5=ma(rows,5,rows.length-2),pm10=ma(rows,10,rows.length-2);
  const ret=(n)=>rows.length>n?(close/rows[rows.length-1-n].close-1)*100:NaN;
  const r3=ret(3),r5=ret(5),r10=ret(10);
  const prev10High=Math.max(...rows.slice(-11,-1).map(x=>x.high));
  const prev20High=Math.max(...rows.slice(-21,-1).map(x=>x.high));
  const break10=close>prev10High*.995, break20=close>prev20High*.995;
  const vol5=avg(rows.slice(-6,-1).map(x=>x.volume)), vr=vol5?cur.volume/vol5:NaN;
  const loc=(cur.close-cur.low)/Math.max(cur.high-cur.low,tick(close));
  const dayRet=(cur.close/prev.close-1)*100;
  const strongDays=rows.slice(-5).reduce((n,r,idx,a)=>{
    if(idx===0){
      const gi=rows.length-5;
      const p=rows[gi-1];
      return n+(p && (r.close/p.close-1)*100>=4 ? 1:0);
    }
    return n+((r.close/a[idx-1].close-1)*100>=4?1:0);
  },0);

  // Latest impulse candle in last 6 sessions.
  let impulse=null;
  for(let k=Math.max(1,rows.length-6);k<rows.length;k++){
    const p=rows[k-1],r=rows[k],dr=(r.close/p.close-1)*100;
    const priorVol=avg(rows.slice(Math.max(0,k-5),k).map(x=>x.volume));
    const rv=priorVol?r.volume/priorVol:1;
    if(dr>=4.5 && r.close>=r.open && rv>=1.0) impulse={idx:k,row:r,dr,rv};
  }
  const supportCandidates=[m5,m10,impulse?.row.low,prev10High].filter(Number.isFinite).filter(x=>x<close);
  const support=supportCandidates.length?Math.max(...supportCandidates):close*.93;
  const stop=roundTick(support-tick(support));
  const risk=(close-stop)/close*100;

  const ii=inst.filter(x=>x.date<=cur.date);
  const inst5=sum(ii.slice(-5).map(instNetRow)), instPrev=sum(ii.slice(-10,-5).map(instNetRow));
  const instImprove=ii.length>=5 && (inst5>0 || inst5>instPrev);

  const mm=margin.filter(x=>x.date<=cur.date);
  let mchg=NaN;
  if(mm.length>=6){
    const now=num(last(mm).MarginPurchaseTodayBalance),old=num(mm[mm.length-6].MarginPurchaseTodayBalance);
    if(old>0)mchg=(now-old)/old*100;
  }

  let momentum=0;
  if(r3>=8)momentum+=10; else if(r3>=5)momentum+=6;
  if(r5>=12)momentum+=8; else if(r5>=7)momentum+=5;
  if(r10>=18)momentum+=5; else if(r10>=10)momentum+=3;
  if(strongDays>=2)momentum+=2;
  momentum=clamp(momentum,0,25);

  let structure=0;
  if(close>m5)structure+=5;
  if(close>m10)structure+=5;
  if(break10)structure+=6;
  if(break20)structure+=5;
  if(loc>=.70)structure+=4;
  structure=clamp(structure,0,25);

  let volume=0;
  if(vr>=1.5)volume+=10; else if(vr>=1.15)volume+=7; else if(vr>=.9)volume+=4;
  if(dayRet>=4&&cur.close>cur.open)volume+=6;
  if(strongDays>=2)volume+=4;
  volume=clamp(volume,0,20);

  let maTurn=0;
  if(m5>pm5)maTurn+=6;
  if(m10>pm10)maTurn+=4;
  if(m5>m10)maTurn+=3;
  if(close>m20)maTurn+=2;
  // No MA20 > MA60 requirement here on purpose.
  maTurn=clamp(maTurn,0,15);

  let chip=0,chipAvail=0;
  if(ii.length>=5){chipAvail+=6;if(instImprove)chip+=6;else if(inst5>instPrev)chip+=3}
  if(Number.isFinite(mchg)){chipAvail+=4;if(mchg<=3)chip+=4;else if(mchg<=8)chip+=2}
  chip=chipAvail?chip/chipAvail*10:5;

  let riskPts=0;
  if(risk>0&&risk<=5)riskPts=5;
  else if(risk<=7.5)riskPts=4;
  else if(risk<=9)riskPts=2;
  riskPts=clamp(riskPts,0,5);

  const factors=[
    ['3/5/10日動能',momentum,25,`3日 ${pct(r3)}｜5日 ${pct(r5)}｜10日 ${pct(r10)}｜近5日強勢日 ${strongDays}`],
    ['價格發動結構',structure,25,`${break10?'突破10T高｜':''}${break20?'突破20T高｜':''}收盤位置 ${fmt(loc*100,0)}%｜MA5 ${fmt(m5)} / MA10 ${fmt(m10)}`],
    ['攻擊量價',volume,20,`今日 ${pct(dayRet)}｜量比 ${fmt(vr,2)}x｜${cur.close>cur.open?'紅K':'黑K'}`],
    ['短均線轉折',maTurn,15,`MA5 ${m5>pm5?'↑':'↓'}｜MA10 ${m10>pm10?'↑':'↓'}｜${close>m20?'已站回MA20':'MA20仍在上方，不直接否決'}`],
    ['籌碼確認',chip,10,`5日法人 ${fmt(inst5/1000,0)} 張｜5筆融資 ${Number.isFinite(mchg)?pct(mchg):'N/A'}`],
    ['發動停損風險',riskPts,5,`動能防守 ${fmt(stop)}｜Risk ${fmt(risk,2)}%`]
  ];
  let score=Math.round(sum(factors.map(x=>x[1])));

  // Avoid one-day dead-cat bounce: require the short-term tape to actually improve.
  const recentLow=Math.min(...rows.slice(-4).map(x=>x.low));
  const oldLow=Math.min(...rows.slice(-10,-4).map(x=>x.low));
  const noNewLow=recentLow>=oldLow*.97 || close>m5;
  const trigger=(break10 || r3>=8 || (strongDays>=2&&r5>=8)) && close>m5 && loc>=.55 && noNewLow;

  let stage='未發動',cls='yellow',position='0%';
  if(score>=74 && trigger && risk<=9){
    stage='反轉發動買進';cls='green';position='10–15%';
  }else if(score>=62 && trigger && risk<=10){
    stage='動能試單';cls='green';position='5–10%';
  }else if(score>=55 && (r3>=5||break10)){
    stage='發動觀察';cls='yellow';position='0–5%';
  }
  return {score,stage,cls,position,factors,stop,risk,r3,r5,r10,break10,break20,vr,strongDays,trigger,inst5,mchg};
}

function classifySetup(rows,a,o){
  const cur=last(rows), prev=rows[rows.length-2];
  const vol5=avg(rows.slice(-6,-1).map(x=>x.volume));
  const volRatio=vol5?cur.volume/vol5:NaN;
  const priorHigh=Math.max(...rows.slice(-41,-1).map(x=>x.high));
  const breakout = cur.close > priorHigh*0.995 && cur.close >= cur.open && volRatio >= 1.15;
  const nearMA10 = Math.abs(cur.close-a.ma10)/cur.close <= 0.025;
  const nearMA20 = Math.abs(cur.close-a.ma20)/cur.close <= 0.035;
  const pullback = cur.close >= a.ma20*0.985 && (nearMA10 || nearMA20) && cur.close >= cur.open*0.985;
  const bullishMA = a.ma5>a.ma10 && a.ma10>a.ma20 && a.ma20>=a.ma60*0.995;
  const structureOK = !a.hardBroken && cur.close >= a.ma20*0.985;
  const overheat = a.bias>18;
  const severeRR = a.rr2<1.5;
  const riskTooHigh = a.risk>8.5;

  // Hard veto only for real structural invalidation / extreme risk.
  if(a.hardBroken || riskTooHigh || severeRR){
    return {state:'NO TRADE',cls:'red',reason:'結構破壞、風險距離過大或中期報酬空間不足'};
  }

  // Breakout setup: allow lower T1 RR if T2 and structure support the move.
  if(breakout && bullishMA && a.score>=72 && a.rr2>=2.2 && a.risk<=6.5 && !overheat){
    return {state:'突破買進',cls:'green',reason:'突破左側前高、量能放大、均線多頭且風險可控'};
  }

  // Pullback setup: reward low-risk entries near rising short/medium MAs.
  if(pullback && bullishMA && o.score>=80 && o.risk<=5.5 && o.rr2>=2.5){
    return {state:'回測買進',cls:'green',reason:'回測 MA10/20 或平台附近，結構未破且風報比改善'};
  }

  // Small probe position when structure is constructive but trigger is incomplete.
  if(structureOK && bullishMA && a.score>=68 && a.risk<=6.5 && a.rr2>=2.0 && a.bias<=15){
    return {state:'試單',cls:'yellow',reason:'結構偏多但突破/回測觸發尚未完整，可小倉位試單'};
  }

  // Constructive but current price is not ideal.
  if(structureOK && o.score>=75){
    return {state:'等待回測',cls:'yellow',reason:'股票結構尚可，但現價安全邊際不足，等候較佳掛單區'};
  }

  return {state:'觀望',cls:'yellow',reason:'尚未出現足夠強的突破或回測訊號'};
}

function combineScores(rows,m,i,d){
  const market=evaluate(rows,m,i,d,'market');
  const optimal=evaluate(rows,m,i,d,'optimal');
  const bottom=bottomReversalEngine(rows,m,i,d);
  const ignition=ignitionEngine(rows,m,i);
  // V1.9.1 Setup only measures structure quality.
  let quality=Math.round(market.score*0.65+optimal.score*0.35);
  quality=clamp(quality,0,100);
  const setup=classifySetup(rows,market,optimal);
  const noTrade=setup.state==='NO TRADE'
    && !['底部反轉買進','底部試單'].includes(bottom.stage)
    && !['反轉發動買進','動能試單'].includes(ignition.stage);
  return {market,optimal,bottom,ignition,quality,noTrade,setup};
}

/* ===== V4.4 Entry Engine =====
   目的：把「股票品質 / 持有品質」與「現在這個價位是否值得進場」分離。
   僅使用審計日及其左側資料，維持 Strict No-Lookahead｜V4 Entry / Hold 分離。
*/
function entryEngine(rows,R){
  const a=R.market,b=R.bottom,ig=R.ignition,cur=last(rows),prev=rows[rows.length-2]||cur;
  const close=cur.close, pclose=prev.close||close;
  const pm5=ma(rows,5,rows.length-2),pm10=ma(rows,10,rows.length-2),pm20=ma(rows,20,rows.length-2);
  const vr=avg(rows.slice(-6,-1).map(x=>x.volume))?cur.volume/avg(rows.slice(-6,-1).map(x=>x.volume)):1;
  const ret1=(close/pclose-1)*100;
  const ret3=rows.length>3?(close/rows[rows.length-4].close-1)*100:0;
  const ret5=rows.length>5?(close/rows[rows.length-6].close-1)*100:0;
  const d5=(close-a.ma5)/close*100, d10=(close-a.ma10)/close*100;
  const atrv=atr(rows), atrPct=atrv/close*100;
  const range=Math.max(cur.high-cur.low,tick(close)), body=Math.abs(cur.close-cur.open);
  const closeLoc=(cur.close-cur.low)/range, bodyPct=body/range;
  const bullish=cur.close>cur.open, hl=higherLow(rows).ok;
  const reclaim5=close>a.ma5&&pclose<=pm5, reclaim10=close>a.ma10&&pclose<=pm10;
  const ma5turn=a.ma5>pm5, ma10turn=a.ma10>pm10, ma20turn=a.ma20>pm20;
  const prev10High=Math.max(...rows.slice(-11,-1).map(x=>x.high));
  const prev20High=Math.max(...rows.slice(-21,-1).map(x=>x.high));
  const break10=close>prev10High, breakout=close>prev20High;
  const limitLike=ret1>=8.5;
  const impulseDay=bullish&&closeLoc>=.65&&((ret1>=5&&vr>=1.05)||(ret1>=3.5&&vr>=1.35));
  const shock=limitLike&&bullish&&closeLoc>=.65;

  // 事件新鮮度：過去5日強K數量。第一根與第三根不能同樣評價。
  let strongDays=0;
  for(let k=Math.max(1,rows.length-5);k<rows.length;k++){
    const r=rows[k],p=rows[k-1],dr=(r.close/p.close-1)*100;
    if(dr>=4.5&&r.close>=r.open)strongDays++;
  }
  const freshEvent=impulseDay&&strongDays<=2;

  // Opportunity = 「這裡是否可能開始一段行情」，不等於現在價格安全。
  let opportunity=0;
  opportunity+=Math.min(22,ig.score*.22);
  opportunity+=Math.min(14,b.score*.14);
  if(shock)opportunity+=28; else if(ret1>=6)opportunity+=21; else if(ret1>=4)opportunity+=14;
  if(vr>=1.8)opportunity+=12; else if(vr>=1.3)opportunity+=9; else if(vr>=1.05)opportunity+=5;
  if(breakout)opportunity+=12; else if(break10)opportunity+=7;
  if(closeLoc>=.75)opportunity+=5;
  if(ma5turn)opportunity+=4;
  if(reclaim5||reclaim10)opportunity+=5;
  if(ret3>=8&&ret3<=18)opportunity+=5;
  if(freshEvent)opportunity+=5;
  if(a.hardBroken&&!shock)opportunity-=25;
  opportunity=clamp(Math.round(opportunity),0,100);

  // Entry Quality = 「今天這個價位下單是否划算」。
  let entryQuality=0;
  if(a.risk<=3)entryQuality+=20; else if(a.risk<=4.5)entryQuality+=16; else if(a.risk<=6.5)entryQuality+=11; else if(a.risk<=8)entryQuality+=5;
  if(a.rr1>=1.5)entryQuality+=8; else if(a.rr1>=1.1)entryQuality+=4;
  if(a.rr2>=3)entryQuality+=12; else if(a.rr2>=2)entryQuality+=8; else if(a.rr2>=1.5)entryQuality+=4;
  if(Math.abs(d5)<=3)entryQuality+=9; else if(Math.abs(d5)<=5)entryQuality+=6; else if(Math.abs(d5)<=7)entryQuality+=2;
  if(Math.abs(d10)<=5)entryQuality+=6;
  if(hl)entryQuality+=6;
  if(reclaim5||reclaim10)entryQuality+=7;
  if(ma5turn)entryQuality+=5;
  if(ma10turn)entryQuality+=3;
  if(vr>=.8&&vr<=1.6)entryQuality+=5;
  if(atrPct<=4.5)entryQuality+=4; else if(atrPct<=6.5)entryQuality+=2;
  entryQuality+=Math.min(10,Math.max(b.score,ig.score)*.10);

  // 強事件可以證明「值得注意」，但只給 Entry 一小段確認分，不直接送到90。
  if(impulseDay)entryQuality+=8;
  if(breakout)entryQuality+=5;

  const chaseReasons=[]; const penalties=[]; let chase=0;
  if(ret5>=22){chase+=10;chaseReasons.push('5日累積漲幅過大')}
  else if(ret3>=18){chase+=7;chaseReasons.push('3日累積漲幅過大')}
  if(d5>=8){chase+=8;chaseReasons.push('距MA5過遠')}
  else if(d5>=6){chase+=4;chaseReasons.push('距MA5偏遠')}
  if(a.bias>15){chase+=7;chaseReasons.push('20MA乖離>15%')}
  if(strongDays>=3){chase+=6;chaseReasons.push('5日內多次強K，已非第一發動')}
  if(closeLoc<.45&&ret1>3){chase+=5;chaseReasons.push('強漲但收盤位置弱')}
  // 第一根真正的 shock 只豁免「當日突然乖離」，不豁免前面已經連漲。
  if(shock&&freshEvent&&ret3<18)chase=Math.max(0,chase-5);

  entryQuality=clamp(Math.round(entryQuality-chase),0,100);

  // Confirmation：要到高品質進場，不能只靠一根K。
  let confirmation=0;
  if(ma5turn)confirmation+=18;
  if(ma10turn)confirmation+=14;
  if(ma20turn)confirmation+=8;
  if(break10)confirmation+=15;
  if(breakout)confirmation+=12;
  if(hl)confirmation+=12;
  if(reclaim10)confirmation+=10; else if(reclaim5)confirmation+=6;
  if(vr>=1.05&&vr<=2.2)confirmation+=6;
  if(closeLoc>=.65)confirmation+=5;
  confirmation=clamp(Math.round(confirmation),0,100);

  // ===== V4.4 Signal Persistence / Follow-through =====
  // 只往左找最近 8 個交易日的「事件K」，絕不讀取審計日右側資料。
  // 目的：第一根強K只取得試單資格；若後續守住事件低點、均線轉強、量縮回檔，
  //       Entry 應逐日升級，而不是每天失憶重新評分。
  let persistence=0, eventAge=null, eventLow=null, eventClose=null, eventHigh=null, eventVol=null;
  const lookback=Math.min(8,rows.length-1);
  for(let age=0;age<=lookback;age++){
    const k=rows.length-1-age;
    if(k<1)break;
    const r=rows[k],p=rows[k-1];
    const dr=(r.close/p.close-1)*100;
    const base=rows.slice(Math.max(0,k-5),k);
    const av=avg(base.map(z=>z.volume))||r.volume;
    const rg=Math.max(r.high-r.low,tick(r.close));
    const loc=(r.close-r.low)/rg;
    const event=(r.close>=r.open && loc>=.62 &&
                ((dr>=5 && r.volume/av>=1.0) || (dr>=3.5 && r.volume/av>=1.35) || dr>=8.5));
    if(event){eventAge=age;eventLow=r.low;eventClose=r.close;eventHigh=r.high;eventVol=r.volume;break;}
  }

  const followReasons=[];
  if(eventAge!==null){
    persistence+=12; followReasons.push(`事件K ${eventAge}日內`);
    const after=rows.slice(rows.length-1-eventAge);
    const minAfter=Math.min(...after.map(z=>z.low));
    const maxClose=Math.max(...after.map(z=>z.close));
    const eventHeld=minAfter>=eventLow*0.985;
    if(eventHeld){persistence+=18;followReasons.push('守住事件K低點')}
    else {persistence-=18;followReasons.push('事件K低點失守')}

    if(close>=eventClose){persistence+=10;followReasons.push('守事件K收盤')}
    else if(close>=eventLow+(eventClose-eventLow)*.5){persistence+=5;followReasons.push('守事件K半身')}

    if(maxClose>eventHigh){persistence+=10;followReasons.push('事件後再創高')}
    if(ma5turn){persistence+=12;followReasons.push('MA5續轉上')}
    if(ma10turn){persistence+=10;followReasons.push('MA10轉上')}
    if(close>a.ma5){persistence+=7;followReasons.push('站穩MA5')}
    if(close>a.ma10){persistence+=5;followReasons.push('站穩MA10')}
    if(hl){persistence+=8;followReasons.push('HL成立')}

    // 事件後正常整理：量縮而價格仍守住事件結構，視為正向確認。
    if(eventAge>=1 && cur.volume<=eventVol*.85 && close>=eventLow){
      persistence+=8; followReasons.push('事件後量縮守穩');
    }
    // 2~6 日內完成確認最有價值；太久則事件影響自然衰減。
    if(eventAge>=2&&eventAge<=6)persistence+=5;
    if(eventAge>=7)persistence-=5;
  }
  persistence=clamp(Math.round(persistence),0,100);

  // Follow-through 不直接把追高價變成好價格；它主要解除「確認不足」問題。
  // 最多提供 18 分升級，仍受 Entry Quality / risk / chase 限制。
  let followBoost=0;
  if(persistence>=75)followBoost=18;
  else if(persistence>=60)followBoost=14;
  else if(persistence>=45)followBoost=9;
  else if(persistence>=30)followBoost=5;

  // Entry Score：只看價格/風險/延續確認；不讀 Setup / Opportunity / Hold。
  // V1.9.1 — Entry is independent from Setup / Opportunity / Hold.
  let score=Math.round(entryQuality*.82+persistence*.18);
  score=clamp(score,0,100);
  const effectiveConfirmation=Math.max(confirmation,Math.round(persistence*.88));

  const triggers=[];
  if(shock)triggers.push('第一強勢事件');
  else if(impulseDay)triggers.push('價格動能脈衝');
  if(breakout)triggers.push('突破20T高');
  else if(break10)triggers.push('突破10T高');
  if(reclaim10)triggers.push('收復MA10'); else if(reclaim5)triggers.push('收復MA5');
  if(hl)triggers.push('HL');
  if(persistence>=45)triggers.push('訊號延續確認');
  if(!triggers.length)score=Math.min(score,58);

  let phase='等待',state='觀望',position='0%';
  if(shock&&freshEvent)phase='事件發動';
  else if(opportunity>=75&&confirmation<50)phase='機會高／確認中';
  else if(opportunity>=70&&entryQuality>=60)phase='早期甜蜜點';
  else if(persistence>=60&&entryQuality>=52)phase='延續確認／可加碼';
  else if(confirmation>=60)phase='確認進場';
  else if(opportunity>=55)phase='預埋觀察';

  if(triggers.length&&!a.hardBroken){
    if(score>=86&&entryQuality>=72){state='高品質進場';position='20–30%'}
    else if(score>=74&&entryQuality>=62){state=persistence>=60?'延續確認加碼':'標準進場';position='10–20%'}
    else if(score>=62){state=shock?'事件型試單':(persistence>=45?'確認試單':'試單');position='5–10%'}
    else if(score>=54){state='預埋觀察';position='0–5%'}
  } else if(shock&&score>=62){
    state='事件型試單';position='5–10%';
  }

  // V1.9.1 Hold is independent: existing-position survivability only.
  let hold=0;
  if(!a.hardBroken) hold+=25;
  if(close>=a.ma20) hold+=18;
  if(close>=a.ma10) hold+=12;
  if(close>=a.ma5) hold+=8;
  if(ma20turn) hold+=10;
  if(ma10turn) hold+=8;
  if(ma5turn) hold+=6;
  if(hl) hold+=8;
  if(a.risk<=7) hold+=5;
  if(a.bias>22) hold-=10;
  if(a.hardBroken) hold-=30;
  hold=clamp(Math.round(hold),0,100);

  return {
    score,state,position,phase,hold,triggers,penalties,
    opportunity,entryQuality,confirmation,effectiveConfirmation,persistence,eventAge,followBoost,followReasons,chasePenalty:chase,chaseReasons,
    route: opportunity>=entryQuality+8?'事件/機會型':'結構/價格型',
    // UI compatibility
    structure:entryQuality,impulse:opportunity,location:entryQuality,rr:0,triggerScore:confirmation,
    setupPart:0,momentum:opportunity,earlyBonus:0,earlyReasons:[]
  };
}

export function createScanRuntime(job,getJSON){
let results=[],errors=[];const scanSamePriceOptions=TWDualAction.samePriceOptions(job.options.samePriceOptions||{});const scanSelection=job.options.selection,scanSelectionWeights=job.options.weights,scanWeights=scanSelectionWeights,scanWeightsValid=true;const scanSelectionDualWeights=job.options.dualWeights||TWDualAction.defaults;
const SCAN_TARGET_DATE=job.targetDate,SCAN_FILTERS=job.options;let SCAN_PROVISIONAL_COUNT=0,SCAN_FORMALIZED_COUNT=0,SCAN_LATEST_MISSING=0;
function selectionScore(r){
  if(scanSelection==='samePrice')return r.samePrice?.schema==='same-price-r31'?(r.samePrice.score??-1):-1;
  if(Object.hasOwn(TWDualAction.selections,scanSelection))return Object.hasOwn(r,'dualSelectionValue')?r.dualSelectionValue:TWDualAction.rank(r,scanSelection,scanSelectionDualWeights);
  if(scanSelection==='action')return TWAction.score(r,scanSelectionWeights);
  if(scanSelection==='actionDelta')return TWAction.delta(r,r.previousScores,scanSelectionWeights);
  if(scanSelection==='holdVolumeDelta')return scanDelta(r,'holdVolumeDelta');
  if(scanSelection==='holdDelta'){
    return Number.isFinite(r.hold)&&Number.isFinite(r.previousScores?.hold)?r.hold-r.previousScores.hold:null;
  }
  return Number.isFinite(r[scanSelection])?r[scanSelection]:null;
}
function selectCandidates(list,limit=Infinity){
  return list.filter(r=>Number.isFinite(selectionScore(r)))
    .sort((a,b)=>selectionScore(b)-selectionScore(a)||(scanSelection==='samePrice'?(b.samePrice?.strength||0)-(a.samePrice?.strength||0):0)||String(a.code).localeCompare(String(b.code)))
    .slice(0,limit);
}
function n(v,d=0){v=Number(v);return Number.isFinite(v)?v:d}
function twTickSize(p){p=Number(p);if(!Number.isFinite(p)||p<=0)return .01;if(p<10)return .01;if(p<50)return .05;if(p<100)return .1;if(p<500)return .5;if(p<1000)return 1;return 5}
function twPrice(p){p=Number(p);if(!Number.isFinite(p))return null;const t=twTickSize(p),v=Math.round(p/t)*t;return Number(v.toFixed(t<.1?2:t<1?1:0))}
function fmtPrice(p){p=twPrice(p);if(p===null)return '—';const t=twTickSize(p);return p.toFixed(t<.1?2:t<1?1:0)}
function fallbackScore(hist){
 const c=hist.at(-1)?.close||0, p=hist.at(-2)?.close||c;
 const ret=p?((c/p)-1)*100:0;
 const ma=k=>hist.slice(-k).reduce((a,x)=>a+n(x.close),0)/Math.min(k,hist.length);
 const m5=ma(5),m10=ma(10),m20=ma(20);
 const trend=(c>m5?20:0)+(m5>m10?25:0)+(m10>m20?25:0)+(ret>0?15:0)+Math.min(15,Math.max(0,ret*2));
 return {setup:Math.round(trend),opportunity:Math.round(trend),entry:Math.round(trend*.8),hold:Math.round(trend),persistence:0,bottom:0,ignition:Math.round(trend),trend:Math.round(trend),state:'fallback'};
}
function findKey(obj,names,depth=0){
 if(obj==null||depth>4)return undefined;
 for(const k of Object.keys(obj)){
   if(names.includes(k.toLowerCase())) return obj[k];
 }
 for(const v of Object.values(obj)){
   if(v && typeof v==='object' && !Array.isArray(v)){
     const z=findKey(v,names,depth+1); if(z!==undefined)return z;
   }
 }
}
function formalObjects(hist,chips={}){
 const rows=hist.map(x=>({date:x.date,open:n(x.open),high:n(x.high),low:n(x.low),close:n(x.close),volume:n(x.volume)}));
 if(typeof combineScores!=='function'||typeof entryEngine!=='function') throw new Error('V4.4 engine functions missing');
 const margin=chips.margin||[],inst=chips.inst||[],daytrade=chips.daytrade||[];
 const R=combineScores(rows,margin,inst,daytrade);
 const E=entryEngine(rows,R);
 return {rows,R,E};
}
function scoreOf(v){
 if(Number.isFinite(Number(v))) return Number(v);
 if(v && typeof v==='object'){
   for(const k of ['score','total','value']){
     if(Number.isFinite(Number(v[k]))) return Number(v[k]);
   }
 }
 return 0;
}
function scoreAt(hist,chips={}){
 try{
   const {R,E}=formalObjects(hist,chips);
   return {
     setup:scoreOf(R?.quality),
     opportunity:scoreOf(E?.opportunity ?? E?.opportunityScore),
     entry:scoreOf(E?.score ?? E?.entryScore),
     hold:scoreOf(E?.hold ?? E?.holdScore),
     persistence:scoreOf(E?.persistence ?? E?.persistenceScore),
     bottom:scoreOf(R?.bottom),
     ignition:scoreOf(R?.ignition),
     trend:scoreOf(R?.market),
     priceGuard:{broken:!!R.market.hardBroken,stop:R.market.stop,risk:R.market.risk},
     state:E?.state ?? R?.state ?? ''
   };
 }catch(e){
   throw new Error('V4.4 engine error: '+(e?.message||e));
 }
}
function formalScore(hist,chips={}){
  const date=String(hist.at(-1)?.date||'');
  const cutChips=d=>Object.fromEntries(['margin','inst','daytrade'].map(k=>[k,(chips[k]||[]).filter(x=>String(x.date)<=d)]));
  const sc=scoreAt(hist,cutChips(date));
  const prior=hist.filter(x=>String(x.date)<date);
  const previousDate=prior.at(-1)?.date||null;
  const previousScores=prior.length>=65?scoreAt(prior,cutChips(previousDate)):null;
  return {...sc,actionSchema:TWDualAction.schema,actionTrail:TWDualAction.history(hist,a=>scoreAt(a,cutChips(a.at(-1).date))),samePrice:TWDualAction.samePrice(hist,chips.inst||[],scanSamePriceOptions),absorption:TWDualAction.absorption(hist,chips.inst||[]),previousDate,previousScores,scoreSchema:TWHoldChange.schema,holdNeedsRefresh:false,
    ...TWHoldChange.calculate(sc,previousScores,hist.at(-1)?.volume,prior.at(-1)?.volume),
    holdVolumeProjected:!!hist.at(-1)?.intradayProjected};
}
function scanDelta(r,key){
  if(r.holdNeedsRefresh||!r.previousScores)return null;
  if(key==='holdVolumeDelta')return Number.isFinite(r.holdVolumeDelta)?r.holdVolumeDelta:null;
  return key==='holdDelta'?(Number.isFinite(r.hold)&&Number.isFinite(r.previousScores.hold)?r.hold-r.previousScores.hold:null):
    (scanWeightsValid?TWAction.delta(r,r.previousScores,scanWeights):null);
}
function priceDecision(hist){
 const a=hist.filter(x=>Number.isFinite(Number(x.close)));
 const last=a.at(-1)||{}, px=n(last.close);
 const avg=k=>a.slice(-k).reduce((s,x)=>s+n(x.close),0)/Math.max(1,Math.min(k,a.length));
 const ma5=avg(5),ma10=avg(10),ma20=avg(20);
 const lows=a.slice(-20).map(x=>n(x.low,x.close)).filter(Boolean);
 const highs=a.slice(-20).map(x=>n(x.high,x.close)).filter(Boolean);
 const recentLow=Math.min(...lows), recentHigh=Math.max(...highs);
 const support=Math.max(...[ma5,ma10,ma20,recentLow].filter(x=>x>0&&x<=px*1.03));
 const buyLow=Math.max(recentLow,Math.min(ma20,ma10,ma5)*0.99);
 const buyHigh=Math.min(px,Math.max(ma5,ma10)*1.01);
 const maxBuy=Math.min(px*1.03,Math.max(ma5,ma10,ma20)*1.035);
 const stop=Math.min(support*0.975,px*0.96);
 const risk=Math.max(.01,px-stop);
 const t1=Math.max(recentHigh,px+risk*1.5);
 const t2=Math.max(t1,px+risk*3);
 const rr1=(t1-px)/risk;
 return {
   ma5,ma10,ma20,buyLow,buyHigh,maxBuy,stop,t1,t2,rr1,
   riskPct:px?risk/px*100:99,
   bias20:ma20?((px/ma20)-1)*100:0
 };
}
async function finmindRecheckOne(r,force=false){
  const end=r._hist?.at(-1)?.date||SCAN_TARGET_DATE||new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});
  const start=new Date(new Date(end+'T12:00:00').getTime()-300*864e5).toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});
  const j=await getJSON(`/api/chips/hybrid?code=${encodeURIComponent(r.code)}&market=${encodeURIComponent(r.market||'twse')}&start_date=${start}&end_date=${end}&require_current=1${force?'&force=1':''}`);
  const chips={margin:j.margin||[],inst:j.inst||[],daytrade:j.daytrade||[]};
  r.preFinmind={setup:r.setup,opportunity:r.opportunity,entry:r.entry,hold:r.hold};
  const sc=formalScore(r._hist,chips); Object.assign(r,sc);
  r.postFinmind={setup:r.setup,opportunity:r.opportunity,entry:r.entry,hold:r.hold};
  r._chips=chips;
  r.finmindWindow={start,end};
  r.finmindSource=j.source||'Official-first hybrid';
  r.finmindCompleteness=j.current_detail?Math.round(Object.values(j.current_detail).filter(Boolean).length/3*100):Number(j.completeness||0);
  r.chipSourceDetail=j.source_detail||{};
  r.chipCompletenessDetail=j.current_detail||{...j.completeness_detail,inst:j.data_dates?.inst===end};
  r.chipDates=j.data_dates||{};
  r.chipCoverageDays=j.coverage_days||{};
  r.finmindAssist=!!j.finmind_assist;
  r.finmindCounts={margin:chips.margin.length,inst:chips.inst.length,daytrade:chips.daytrade.length};
  return r;
}
function scanMinutes(hms){const m=String(hms||'').match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null}
function scanTaipeiNow(){
  const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());
  const o={};for(const p of parts)o[p.type]=p.value;
  return {date:`${o.year}-${o.month}-${o.day}`,minutes:Number(o.hour)*60+Number(o.minute)};
}
function scanMarketOpen(j,b){
  const now=scanTaipeiNow();
  if(String(b?.date||'')!==now.date)return false;
  return Number.isFinite(now.minutes)&&now.minutes>=540&&now.minutes<810;
}
function scanQuoteErrors(j,b){const errs=[...(j?.validation_errors||[])],pos=v=>{const x=Number(v);return Number.isFinite(x)&&x>0?x:null};const o=pos(b?.open),h=pos(b?.high),l=pos(b?.low),c=pos(b?.close);if(o===null)errs.push('open invalid');if(h===null)errs.push('high invalid');if(l===null)errs.push('low invalid');if(c===null)errs.push('close invalid');if(h!==null&&l!==null&&l>h)errs.push('low > high');return [...new Set(errs)]}
function scanProjectedVolume(currentVol,lastTime,avg5,open){const mins=scanMinutes(lastTime);if(!open||!Number.isFinite(mins)||mins>=810)return {volume:n(currentVol),fraction:1};const elapsed=Math.max(1,Math.min(270,mins-540)),frac=Math.max(.03,elapsed/270),linear=n(currentVol)/frac,conf=Math.max(.28,Math.min(1,elapsed/120)),base=n(avg5)>0?n(avg5):linear;return {volume:Math.max(n(currentVol),Math.round(linear*conf+base*(1-conf))),fraction:frac}}
function chipCutForLive(arr,date,open){return (arr||[]).filter(x=>{const d=String(x?.date||'');return open?d<date:d<=date})}
async function liveCurrentRecheckOne(r){
  const j=await getJSON(`/api/intraday?code=${encodeURIComponent(r.code)}&market=${encodeURIComponent(r.market||'twse')}`);
  let b=j.bar||{};
  const completed=(r._hist||[]).find(x=>x.date===b.date&&!x.intradayProjected);
  if(!scanMarketOpen(j,b)&&r.formalPrice&&completed)b={...b,...completed};
  const errs=scanQuoteErrors(j,b);
  if(j.quote_valid===false||errs.length)throw new Error(`盤中報價異常 ${errs.join('/')}`);
  if(String(b.date)<String(r.dataDate||''))throw new Error('報價日期落後，保留既有資料');
  const open=scanMarketOpen(j,b);let base=(r._hist||[]).filter(x=>String(x.date)<String(b.date));
  if(base.length<65)throw new Error('盤中基準K不足');
  const avg5=base.slice(-5).reduce((sum,x)=>sum+n(x.volume),0)/Math.max(1,Math.min(5,base.length)),pv=scanProjectedVolume(n(b.volume),b.last_time,avg5,open);
  const liveBar={date:b.date,open:twPrice(b.open),high:twPrice(b.high),low:twPrice(b.low),close:twPrice(b.close),volume:Math.round(pv.volume),turnover:0,intradayProjected:open},sim=base.concat([liveBar]);
  const raw=r._chips||{margin:[],inst:[],daytrade:[]},chips={margin:chipCutForLive(raw.margin,b.date,open),inst:chipCutForLive(raw.inst,b.date,open),daytrade:chipCutForLive(raw.daytrade,b.date,open)},sc=formalScore(sim,chips);
  delete r.liveError;r.liveActualVolume=n(b.volume);r.formalBeforeLive={setup:r.setup,opportunity:r.opportunity,entry:r.entry,hold:r.hold};Object.assign(r,sc);r.close=twPrice(b.close);r.dataDate=b.date;r.liveCurrent=true;r.liveTime=b.last_time||'';r.liveProjectedVolume=Math.round(pv.volume);r.liveVolumeRatio=avg5?pv.volume/avg5:null;r.liveMarketOpen=open;r.liveSource=j.source||'Yahoo Finance 1m intraday';r._hist=sim;r._chips=chips;r.decision=priceDecision(sim);return r;
}
async function stage1CurrentHistory(code,market,start,end){
  // Scalable path: cached Yahoo Daily first. If it lags the market-data target,
  // append the completed/current Yahoo 1m bar. No per-stock TWSE monthly request here.
  const j=await getJSON(`/api/history/auto?code=${encodeURIComponent(code)}&market=${encodeURIComponent(market)}&start_date=${start}&end_date=${end}`);
  let hist=(j.data||[])
    .map(x=>({...x,open:twPrice(x.open),high:twPrice(x.high),low:twPrice(x.low),close:twPrice(x.close)}))
    .filter(x=>Number.isFinite(Number(x.close))&&Number(x.close)>0);
  if(hist.length<180) throw new Error(`歷史K不足 ${hist.length}`);
  const last=hist.at(-1);
  const completed=hist.filter(z=>String(z.date)<String(SCAN_TARGET_DATE)).at(-1)||last;
  const lastFormalDate=completed?.date||null;
  const lastFormalVolume=Math.max(0,n(completed?.volume,0));
  let provisional=false,liveSource=null;
  if(SCAN_TARGET_DATE && String(last?.date||'')<String(SCAN_TARGET_DATE) && lastFormalVolume/1000<SCAN_FILTERS.minLots){
    throw new Error(`低於最低成交量 ${(lastFormalVolume/1000).toFixed(0)}張（前一正式日）`);
  }

  if(SCAN_TARGET_DATE && (String(last?.date||'')<String(SCAN_TARGET_DATE)||(SCAN_TARGET_DATE===scanTaipeiNow().date&&scanMarketOpen({}, {date:SCAN_TARGET_DATE})))){
    const iq=await getJSON(`/api/intraday?code=${encodeURIComponent(code)}&market=${encodeURIComponent(market)}`);
    const b=iq.bar||{},errs=scanQuoteErrors(iq,b);
    if(iq.quote_valid===false||errs.length||String(b.date)!==String(SCAN_TARGET_DATE)){
      SCAN_LATEST_MISSING++;
      throw new Error(`最新K缺失 ${last?.date||'—'}（Target ${SCAN_TARGET_DATE}）`);
    }
    const prior=hist.filter(z=>String(z.date)<String(b.date));
    const avg5=prior.slice(-5).reduce((sum,z)=>sum+n(z.volume),0)/Math.max(1,Math.min(5,prior.length));
    const open=scanMarketOpen(iq,b),pv=scanProjectedVolume(n(b.volume),b.last_time,avg5,open);
    const bar={date:b.date,open:twPrice(b.open),high:twPrice(b.high),low:twPrice(b.low),close:twPrice(b.close),
      volume:Math.max(0,Math.round(pv.volume)),turnover:0,stage1Provisional:true,formalVolume:false,intradayProjected:open};
    hist=hist.filter(z=>String(z.date)<String(bar.date)).concat([bar]);
    provisional=true; liveSource=iq.source||'Yahoo Finance 1m';
    SCAN_PROVISIONAL_COUNT++;
  }
  return {hist,source:j.source,provisional,liveSource,lastFormalDate,lastFormalVolume};
}

async function formalizeListedOne(r){
  if(scanSelection==='samePrice'&&r.samePriceChecked)return r;
  if(r.market!=='twse') return r;
  const end=SCAN_TARGET_DATE||new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});
  const start=new Date(new Date(end+'T12:00:00').getTime()-470*864e5).toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});
  try{
    const j=await getJSON(`/api/history/auto?code=${encodeURIComponent(r.code)}&market=twse&start_date=${start}&end_date=${end}&fresh=1&_=${Date.now()}`);
    let hist=(j.data||[]).map(z=>({...z,open:twPrice(z.open),high:twPrice(z.high),low:twPrice(z.low),close:twPrice(z.close)}))
      .filter(z=>Number.isFinite(Number(z.close))&&Number(z.close)>0);
    const projected=r._hist?.at(-1);
    if(projected?.intradayProjected && projected.date===SCAN_TARGET_DATE && scanMarketOpen({},projected)){
      hist=hist.filter(z=>String(z.date)<String(projected.date)).concat([{...projected}]);
    }
    if(hist.length>=180 && (!SCAN_TARGET_DATE || String(hist.at(-1)?.date)===String(SCAN_TARGET_DATE))){
      r._hist=hist;
      Object.assign(r,formalScore(hist,r._chips||{}));
      const last=hist.at(-1); r.close=twPrice(last.close); r.dataDate=last.date; r.decision=priceDecision(hist);
      r.prelimScore=selectionScore(r); r.stage1Provisional=!!last.intradayProjected; r.formalPrice=!last.intradayProjected;
      SCAN_FORMALIZED_COUNT++;
    }
  }catch(e){ r.formalPriceError=e.message||String(e); }
  return r;
}
async function worker(item){
  const code=String(item.code||item.stock_id||'').trim();
  if(!code){errors.push('候選股缺少代號');return}
  try{
    const end=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});
    const start=new Date(Date.now()-470*864e5).toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});
    const market=item.market||'twse';
    const sh=await stage1CurrentHistory(code,market,start,end);
    let hist=sh.hist;
    const lastBar=hist.at(-1)||{};
    const latestClose=n(lastBar.close,0);
    // Audit proved Yahoo 1m volume can materially undercount official Daily volume.
    // If Target-day K is provisional, use the previous completed Daily volume only
    // for the liquidity filter. Target-day price/structure still uses the latest K.
    const liquidityVolume=sh.provisional?sh.lastFormalVolume:n(lastBar.volume,0);
    const liquidityLots=liquidityVolume/1000;
    if(latestClose<SCAN_FILTERS.minClose)throw new Error(`低於最低股價 ${latestClose}`);
    if(SCAN_FILTERS.maxClose>0&&latestClose>SCAN_FILTERS.maxClose&&!item.hasFutures)throw new Error('超過最高股價');
    if(liquidityLots<SCAN_FILTERS.minLots)throw new Error(`低於最低成交量 ${liquidityLots.toFixed(0)}張（${sh.provisional?'前一正式日':'正式日'}）`);
    const s=formalScore(hist);
    for(const k of ['setup','opportunity','entry','hold']){
      const v=Number(s[k]);
      if(!Number.isFinite(v)||v<0||v>100) throw new Error(`模型輸出異常 ${k}=${s[k]}`);
    }
    const last=hist.at(-1);
    const rr={
      ...item,
      code,
      name:item.name||item.stock_name||code,
      close:twPrice(last.close||item.close||0),
      ...s,
      decision:priceDecision(hist),
      historyCount:hist.length,
      historySource:sh.source,
      stage1Provisional:sh.provisional,
      stage1LiveSource:sh.liveSource,
      liquidityDate:sh.provisional?sh.lastFormalDate:last.date,
      liquidityLots:Math.round(liquidityLots),
      dataDate:last.date,
      yahooLast:null,
      latestTwseDate:null,
      latestMerge:sh.provisional?'Yahoo 1m Stage1 provisional':'Yahoo Daily',
      marketResolved:market,
      _hist:hist,
      finmindCompleteness:0
    };
    if(SCAN_TARGET_DATE && String(rr.dataDate)!==String(SCAN_TARGET_DATE)){
      throw new Error(`Stage1日期不一致 ${rr.dataDate||'—'}（Target ${SCAN_TARGET_DATE}）`);
    }
    if(scanSelection==='samePrice'){
      await formalizeListedOne(rr);
      try{await finmindRecheckOne(rr);rr.samePriceChecked=true}
      catch(e){rr.chipError=String(e.message||e);rr.samePrice={schema:'same-price-r31',score:null,state:'取得失敗',detail:'法人來源取得失敗，請更新籌碼',priceDate:rr.dataDate};}
    }
    rr.prelimScore=selectionScore(rr);
    results.push(rr);
  }catch(e){
    errors.push(`${code}: ${e.message||e}`);
  }
}

return {selectionScore,selectCandidates,formalScore,formalizeListedOne,finmindRecheckOne,liveCurrentRecheckOne,
 async scan(item){results=[];errors=[];await worker(item);return {row:results[0]||null,error:errors[0]||null}},
 counters:()=>({provisional:SCAN_PROVISIONAL_COUNT,formalized:SCAN_FORMALIZED_COUNT,missing:SCAN_LATEST_MISSING})};
}
